### ISSUE TITLE
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by fokosun** [vuejs-templates/webpack#1139]
I created a new app using vue cli
vue init webpack appname
cd appname
npm install && npm run dev

Everything worked as expected in dev until I deployed to heroku

Now I am getting this error:
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

Following that url, I am using webpack 3.

I have not been able to find a fix for this. A nudge in the right direction will be helpful. Thanks

**Comment by LinusBorg** [comment]
1. Why would you build *on* heroku?
2. What command did you run on heroku? did you by any chance do this?

```
NODE_ENV=production npm run dev 
```

That would start a dev server with a *development* configuration that breaks because the *development* config won't work with `NODE_ENV=production`

And running the dev server on heroku doesn't make any sense anyway.

**Comment by fokosun** [comment]
@LinusBorg 
When you deploy to heroku, first the dependencies are installed then start and postinstall commands. My start script runs my server.js which runs express server and the postinstall script run the build command. Problem was the build only created dist/static and didn't create dist/index.html. The error was because dist/index.html was not found. 

Fixed it. Thanks

**Comment by bum** [comment]
I get over this problem today as follow the "npm run dev" command. They use "process.env.NODE_ENV === 'production'" to detect running mode, but as I checked npm config get production (get false), but when I check the windows enviroment variables NODE_ENV=development, but it still failed.
The problem is that there's another variable named BABEL_ENV=production. I changed it to BABEL_ENV=development and restart windows (to make sure it updated), then everything runs as design.
